name: BlockQuest
version: 2.2.3
main: me.robifoxx.blockquest.BlockQuest
softdepend: [PlaceholderAPI, Multiverse-Core]
api-version: 1.13

commands:
    blockquest:
        description: Use this to add/remove blocks
        permission: blockquest.command
permissions:
    blockquest.command:
        description: Access to the /blockquest command
        default: op
