# Unsafe save:
# When it's true, stats will be saved when
# player leaves (when MySQL is enabled), or
# when server disables.
# However, when false, it will save when
# player finds a reward.
# -----------------------------------
# If hide-found-blocks is "NONE", it will
# be disabled.
# -----------------------------------
# For custom skulls for find effect,
# use the Base64 Encoding
# from heads.freshcoal.com in the give command,
# what usually looks like this:
# eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzAxNDYxOTczNjM0NTI1MTk2ZWNjNzU3NjkzYjE3MWFkYTRlZjI0YWE5MjgzNmY0MmVhMTFiZDc5YzNhNTAyZCJ9fX0=
# -----------------------------------
# You can use DISABLED or NONE for some
# paths to disable it.
# -----------------------------------

placeholderapi: false
use-mysql: false
enabled: false
disabled-msg: '&cBlocks aren''t enabled yet! If you are a player, refer to a Server Administrator!'

use-uuid: true
check-full-inventory: 0
full-inventory-msg: '&c&lYour inventory is full!'

mysql-host: host
mysql-database: database
mysql-username: username
mysql-password: password
mysql-unsafe-save: true

no-permission: '&cYou don''t have permission for this!'

hide-found-blocks: NONE
blocks: []

find-block-commands:
    - particle mobSpell %locX% %locY% %locZ% 0.25 0.25 0.25 1 10
    - rawmsg %player% true &a&lBlock&2&lQUEST
    - rawmsg %player% false &a
    - rawmsg %player% true &fYou found a block!
    - rawmsg %player% true &f%blocksLeft% left.
    - give %player% diamond 1

all-blocks-found-commands:
    - rawmsg %player% true &a&lBlock&2&lQUEST
    - rawmsg %player% false &a
    - rawmsg %player% true &fYou found &lALL &fblocks!
    - rawmsg %player% true &fNice!
    - give %player% diamond_block 1

already-found-commands:
    - rawmsg %player% true &a&lBlock&2&lQUEST
    - rawmsg %player% false &a
    - rawmsg %player% true &fYou already found this block!

already-found-all-blocks:
    - rawmsg %player% true &a&lBlock&2&lQUEST
    - rawmsg %player% false &a
    - rawmsg %player% true &fYou already found all blocks!

find-effect:
    enabled: true
    invisible: true
    small: true
    custom-name: ''
    head: PUMPKIN
    chest: NONE
    leg: NONE
    boot: NONE
    particle: FLAME
    loop: 30
    levitation-per-loop: 0.2
    yaw-rotation: 20
    scheduler: 2
    y-start: 0.25
    sound: ENTITY_FIREWORK_LAUNCH
    sound-pitch: 0
    disappear-commands:
        enabled: false
        commands:
            - 'say The find effect disappeared at %locX% %locY% %locZ%!'

particles:
    loop: 20
    enabled: false
    found:
        dx: 0.05
        dy: 0.05
        dz: 0.05
        speed: 0.1
        quantity: 20
        type: DISABLED
    notfound:
        dx: 0.05
        dy: 0.05
        dz: 0.05
        speed: 0.1
        quantity: 35
        type: FLAME