name: BlockQuest
version: 2.0-pre1.1
main: me.robifoxx.block.Main
softdepend: [PlaceholderAPI]

commands:
    blockquest:
        description: Use this to add/remove blocks
        permission: blockquest.command
permissions:
    blockquest.command:
        description: access to the /blockquest command
        default: op
